sudo: required

language: java

services:
  - docker

script: mvn install -P jar

env:
   global:
      - secure: "ORWExWR0fVSKV4osTAuO/hXq5JWQv1fNea2HfCSlodmbtPag4cdPJai9gbkp2BW6Z59jYfiztmr9MttuKLwnH/BlFaMkeWhlwQYgTYw67h4jljg0H4rE6mwaup5Ccej3phFu6iVbFR6IYwJIyUl8a2qjrXvvx3EfW5GiyxBsQc/R+RxC0bTjnEEKBy0XpZkO0JhThefjOVx8ZMT/4xPCIR9Uk92C47PXOf3TiFvmRyDyDDM9qCkvynUnkH5r3XOlO1/EE9ITL6WTXhhTwjtznwJXvrdXYjE3aZIO6hQJgx+6TtT1V7FignHrhz5RHAYNxty8nefjxTrxEJoM7kj6/g7O9fcGfXxsrdm13ZBWtSbY+YmxIQgM/ghFLTdDYL/zo0PFT7Aeo+sMbTqF1eF625FaLevNsHajZwv/TU2JcC0dw1qD3FPRy5ng4zO4jyCcYi1CjIzRP91QV4i7sJA4mJOsO1kh6jx5iCJ1+G7CpWiKfQpJ3gJ/MWDo5b6zj7K5aAF24CGlCzMatSuOemgJIBUPP3Pikl9K5B2KRacIkwCOhTXqP3ArZszXzqYLCn8XOpMl3k7gnAvPnwh/4WDAOYwJkuNXd6yqsoEzMGtbuMhF8tFwXvJBFYDhSqBWCuefUxDYMtJuwy0n+A2qmTxam3t4dq8j3gIl2Es1aeQE/uk=" # DOCKER_EMAIL
      - secure: "AgT8dktFskwo0KBL+xlHGasxI9DaHGPqAyQpBz2ulVWWpXoxNLPWRtZtVU6QmaA+M6Ve7k8kSVJS4jbdtc9xQoKmS4FvAkufAqPkxcTYK2HDrgM+Z/A2aKjvG/FVuyuwauDVyOnyIPvvKofzBNfG/5vW5pp39DZO9O2xL0B+v2e0/KoCZHNnPS7K6GH4cY88XqJU4E9W6z+9jBr5WphtXmKCQO9ZNX9GJSnpB/N7ZjRW++1B04Cow6mSr1pouQwtLzAwCPbOmmGVRrgXB3p3rLdQQtR/bgGnV/ffXUbdKdcPhw0OW0sLqn3x7o96s44g/OqvVrda3++FnUdcv4L1haJdkEVxJ7KaGTCLzrA58aJwPGXy1gFNoRwu0PTv09l+X+M1MQgnKN1MvK2iqXCa13Ho74u+jBnKojYN4cpwO3FZcmhT7c27fkKQwd4LEOpC9UpH9vMgKrWGD9xFvHRTAKXox0kOIcQ/Y31EYTCQxg9I7CwwrXp6DuO58IUSZVVz5Et70YwHzdYr6xmIrrv5gR7/Yzo6s/vyYM/8KwaBpnbLE10N4HunQXcpk8i7urDITNPdqn8LxrRob5fcmbJXb8d/62l0f9KAqf4eIDk/wFuLuZWUn1ogT9j6dtGJpr1BOCVj++ZHijhypBoTGcVzzSDMo1Ubfc+CQtTDY0lGt7U=" DOCKER_USER
      - secure: "pfeDfv79uMfuK8QJVs7o/5P/HgB9XKqB0yvmoTpNRkCD3Wy12xMFYsUV/zyNXuZEOKhdrv3Nn/Z5tpKX4pSNgetIkfmdaNtVxcHfxpd9a4zwzlC3YxAXzuW+0rjozKFwMEGZRY+/I6Bxkc2EH/MJ/a9AZlt1DgVypt9KB627+YSw850h45LUGd9SF0ukPmFrXjkvKGtnlCs9w54+6RCI3OnN/HxVJqIqb02OTh3evNfbnC89/Z9xBSKabv55Fn7vFQUcMTguuKWKMHPwquWnoabofjWha29F9PRVRtAAcqew7HE1M6yJqoc1U4DsnfK0AmT7y3xaDQv5vgcDyd9rzNq9QHnW3mtpD3SouJjFI2dQEiFv3UXjh42gWFHU08CYCbB8xDddW0avg9KD1iuLEDKFRMhWhuFB+PWCsIFN43kjvBXz8Gcf/MgAx9uGk28ZVFB39mN5QghDp5K11eV60jf1fOhrnpf2VGeGb5J1YFHX4Q1LwxepZv06AmAjxuLN0wzcm6EtLFbLbDrc3iRHoZ7xfuIAwZc9FYzksUNh0MZ8w1XOimKe7BvdroTQZbmHXs1qKIzSsyuaoSGoGQyizVDn62ZGDpiojWbCVdJQJS8lFyHAXRtF1bQm6/hp42wiOgGSx2GmulRh4NNkPyKG9YAaCSlhLDr9KhfcIv4tPjk=" # DOCKER_PASS
      - COMMIT=${TRAVIS_COMMIT::8}

after_success:
   - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
   - export REPO=dmopensource/selavi
   - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
   - docker build -f Dockerfile -t $REPO:$COMMIT .
   - docker tag $REPO:$COMMIT $REPO:$TAG
   - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
   - docker push $REPO
